config/routes.rb
Rails.application.routes.draw do

  get '/auth/:provider/callback' => 'sessions#omniauth'

  get '/' => 'sessions#welcome'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/signup' => 'users#new' 
  delete '/logout' => 'sessions#destroy'

  get '/notes/most_recent' => 'notes#most_recent'
  get '/notes/random_note' => 'notes#random_note'
  get '/songs/find_specific' => 'songs#find_specific'
  resources :notes

  resources :operas

  resources :songs do
    resources :notes, only: [:new, :create, :index, :show]
  end 

  resources :users
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :song
  belongs_to :user
  validates :title, presence: { message: "please be sure to fill in all of the fields"}
  validates :content, presence: { message: "please be sure to fill in all of the fields"} 

  ## this scope method allows us to call most recently published note 
  def self.most_recent
    self.order('created_at desc').first
  end

  def self.random_note
    self.all.sample 
  end 



  


end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :redirect_if_not_logged_in, only: [:index, :show]
  before_action :find_note, only: [:show, :edit, :update, :destroy]

  def new
    @song = Song.find_by_id(params[:song_id])
    @note = Note.new(song_id: @song.id)
  end

  def create
    @song = Song.find_by_id(params[:song_id])
    @note = current_user.notes.build(note_params)
      if @note.save
        redirect_to song_path(@song)
      else 
        render :new
      end 
  end 

  def index
    @song = Song.find_by_id(params[:song_id])
    @notes = @song.notes 
  end 

  def show 
    @song = Song.find_by_id(params[:song_id])
    @notes = Note.all 
  end 

  def most_recent
    @note = Note.most_recent
    render :show
  end 

  def random_note
    @note = Note.random_note 
    render :show 
  end 

  def edit
    if @note.user_id != current_user.id 
      @error = "this is not your note - editing is not permitted"
      render :show
    end 
  end 

  def update
    @note.update(note_params)
      if @note.valid? 
        redirect_to note_path
      else 
        render :edit
      end 
  end 

  def destroy
    @note.destroy
    redirect_to notes_path
  end 

  private

    def note_params
    params.require(:note).permit(:title, :content, :song_id, :user_id)
  end 

  def find_note
    @note = Note.find_by_id(params[:id])
  end 

end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_form.html.erb
<%= form_for([@song, @note]) do |f| %><br>
  note title 
  <%= f.text_field :title %><br>
  wrote your note here 
  <%= f.text_area :content %>
  <%= f.hidden_field :song_id %><br>
  <%= f.submit %>
<% end %>

app/views/notes/edit.html.erb
<h2>edit note</h2>

<br><br>
<%= render partial: 'layouts/errors', locals: {object: @note} %>
<br><br>

<%= render partial: 'form' %>

app/views/notes/index.html.erb
<h1>all notes</h1>


<p><% @notes.each do |note| %><p> 
  <%= link_to(note.title, note_path(note.id) ) %>
<% end %>

app/views/notes/new.html.erb
<h2>write a new note</h2>

<br><br>
<%= render partial: 'layouts/errors', locals: {object: @note} %>
<br><br>

<%= render partial: 'form' %>

app/views/notes/show.html.erb
<h1><%= @note.title %></h1>
<p><%= @note.content %></p>

<br><br>
<%= @error %>
<br><br>

<p><%= link_to "edit this note", edit_note_path(@note) %></p>
<p><%= link_to "delete note", note_path(@note), method: 'delete' %><p>