config/routes.rb
Rails.application.routes.draw do

  get '/auth/:provider/callback' => 'sessions#omniauth'

  get '/' => 'sessions#welcome'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/signup' => 'users#new' 
  delete '/logout' => 'sessions#destroy'

  get '/notes/most_recent' => 'notes#most_recent'
  get '/notes/random_note' => 'notes#random_note'
  get '/songs/find_specific' => 'songs#find_specific'
  resources :notes

  resources :operas

  resources :songs do
    resources :notes, only: [:new, :create, :index, :show]
  end 

  resources :users
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :opera
  belongs_to :user
  has_many :notes
  has_many :users, through: :notes 
  validates :title, presence: { message: "cannot be blank"}
  validates :opera_id, presence: { message: "cannot be blank"}
  # this method needs to find a song where the first letters in its title
  # match the input into the text field 
  scope :find_specific, ->(title) { where('title LIKE ?', "%#{title}%") } 

  # presence true, length etc
  # make a partial for errors 

  def title_and_opera
    "#{self.title} - #{self.opera.name}"
  end 

 # accepts_nested_attributes_for :opera

  def opera_attributes=(attr_hash)
    self.opera = Opera.find_or_create_by(attr_hash)
  end 

  # def find_specific_songs
  #   self.where
  # end 

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :redirect_if_not_logged_in, only: [:new, :index, :show, :edit]
  before_action :find_song, only: [:show, :edit, :update]

    def new
      @song = Song.new
      @song.build_opera
    end

    def create
      @song = @current_user.songs.build(song_params)
      
      # @song = Song.new(song_params)
      
      # @song.user_id = session[:user_id]
      
        if 
          @song.save
          redirect_to song_path(@song)
        else 
          render :new 
        end 

    end 

    def index
      @songs = Song.all
    end 

    def find_specific
      @songs = Song.find_specific(params[:query])
      render :index 
    end 

    def show
    end 

    def edit
    end 

    def update
      @song.update(song_params)
        if @song.valid? 
          redirect_to song_path
        else
          render :edit
        end 
    end 

    def destroy
      if @song.user_id != current_user.id
        redirect_to song_path
      else
      @song.destroy
      redirect_to songs_path
      end 
    end 

    private

    def song_params
      params.require(:song).permit(:title, opera_attributes: [:name])
    end 

    def find_song
      @song = Song.find(params[:id])
    end 

end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/songs/_form.html.erb
<p><%= @error %></p>


<%= form_for(@song) do |f| %>
  <div>
    song title
    <%= f.text_field :title %>
  </div>
  <br>
  <div>

opera name 
  <%= f.fields_for :opera do |o| %>
  <%= o.text_field :name %>
<% end %>

</div>

  <br>
  <%= f.submit %>
<% end %>

app/views/songs/edit.html.erb
<h1> edit song </h1>

<br><br>
<%= render partial: 'layouts/errors', locals: {object: @song} %>
<br><br>

<%= render partial: 'form' %>

app/views/songs/index.html.erb
<h1> all songs </h1>

<%= form_with url: "/songs/find_specific", method: :get do |form| %>
<%= form.label :query, "search for" %>
<%= form.text_field :query %>
<%= form.submit "search" %>
<% end %>

<% @songs.each do |song| %>
  <p><%= link_to(song.title_and_opera, song_path(song.id) )%></p>
<% end %>

app/views/songs/new.html.erb
<h1> add a new song </h1>

<br><br>
<%= render partial: 'layouts/errors', locals: {object: @song} %>
<br><br>

<%= render partial: 'form' %>

app/views/songs/show.html.erb
<h1><%= @song.title %></h1>

from the opera <h2> <%= @song.opera.name %></h2> 
<p><%= link_to "see the notes that have been written about this song", song_notes_path(@song) %></p>
<p><%= link_to "edit this song's information", edit_song_path(@song) %></p>
<p><%= link_to "write a new note about this song", new_song_note_path(@song) %></p>
<p><%= link_to "delete song", song_path(@song), method: 'delete' %><p>