config/routes.rb
Rails.application.routes.draw do

  get '/auth/:provider/callback' => 'sessions#omniauth'

  get '/' => 'sessions#welcome'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/signup' => 'users#new' 
  delete '/logout' => 'sessions#destroy'

  get '/notes/most_recent' => 'notes#most_recent'
  get '/notes/random_note' => 'notes#random_note'
  get '/songs/find_specific' => 'songs#find_specific'
  resources :notes

  resources :operas

  resources :songs do
    resources :notes, only: [:new, :create, :index, :show]
  end 

  resources :users
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/opera.rb
class Opera < ApplicationRecord
    has_many :songs 
    validates :name, presence: true


# custom writer method so that a new object isn't instantiated every time
# and the object isn't duplicated in DB 
    def opera_attributes=(attributes)
       self.opera = Opera.find_or_create_by(attributes) if !attributes['name'].empty?
       self.opera
    end
end

app/controllers/operas_controller.rb
class OperasController < ApplicationController
    before_action :redirect_if_not_logged_in, only: [:show, :index]

    def show
        @opera = Opera.find(params[:id])
    end 

    def index
        @operas = Opera.all 
    end 

    def destroy
        @opera = Opera.find(params[:id])
        @opera.destroy
        redirect_to operas_path
    end 
    
end

app/helpers/operas_helper.rb
module OperasHelper
end

app/views/operas/index.html.erb
<h1>all operas</h1>

<p> <% @operas.each do |opera| %> </p>
<%= link_to opera.name, opera_path(opera.id ) %>
<% end %>

app/views/operas/show.html.erb
<h2><%= @opera.name %></h2>

<p> <% @opera.songs.each do |song| %> </p>

<h3> <%= link_to song.title, song_path(song.id) %></p></h3>


<% end %>


<%= link_to "delete opera", opera_path(@opera), method: 'delete' %>