config/routes.rb
Rails.application.routes.draw do

  get '/auth/:provider/callback' => 'sessions#omniauth'

  get '/' => 'sessions#welcome'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/signup' => 'users#new' 
  delete '/logout' => 'sessions#destroy'

  get '/notes/most_recent' => 'notes#most_recent'
  get '/notes/random_note' => 'notes#random_note'
  get '/songs/find_specific' => 'songs#find_specific'
  resources :notes

  resources :operas

  resources :songs do
    resources :notes, only: [:new, :create, :index, :show]
  end 

  resources :users
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
<div id="error_explanation">
    <h5><%= pluralize(object.errors.count, "error") %> prohibited this from being saved:</h5>
    <ul>
    <% object.errors.full_messages.each do |message| %>
    <li><%= message.downcase %></li>
    <% end %>
    </ul>
</div>
<% end %>

app/views/layouts/_logged_in_links.erb
    <div>
      <br><br>
      <%= link_to "add a new song", new_song_path %>  |
      <%= link_to "view all songs", songs_path %> |
      <%= link_to "view all operas", operas_path %> |
      <%# <%= link_to "view most recent note", note_path(Note.most_recent.id) %> 
      <%= link_to "view most recent note", notes_most_recent_path %> |
      <%= link_to "view a random note", notes_random_note_path %> |
      <%= link_to "home", user_path(current_user.id) %> |
      <%= link_to "log out", logout_path, method: :delete %> 
    </div>

app/views/layouts/_logged_out_links.erb
<div>
<br><br><br>
  <%= link_to "login", login_path %>
  <%= link_to "sign up", signup_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OperaDb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
 <div><%= render_nav_bar %></div>
  <body>

    <%= yield %>

  </body>
</html>